package pl.superCinema.backend.domain.model;

public enum Type {
    SF, COMEDY, HORROR, ROMANCE, ACTION, THRILLER, DRAMA, MYSTERY, CRIME,
    ANIMATION, ADVENTURE, FANTASY, COMEDY_ROMANCE, ACTION_COMEDY, SUPERHERO,
    HISTORICAL, MUSICAL,WESTERNS, POLITICAL,

}
