package pl.superCinema.backend.infrastructure.dto;

public enum TypeDto {
    SF, COMEDY, HORROR, ROMANCE, ACTION, THRILLER, DRAMA, MYSTERY, CRIME,
    ANIMATION, ADVENTURE, FANTASY, SUPERHERO,
    HISTORICAL, MUSICAL,WESTERNS, POLITICAL,

}
